services:
    frontend:
        image: interexy-1:latest
        ports:
            - 8080:8080
    db:
        image: postgres:latest
        container_name: pgsdb
        environment:
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: "secret"
            POSTGRES_DB: "base123"
            PGADMIN_LISTEN_ADDRESS: 0.0.0.0
        volumes:
            - data:/var/lib/postgresql/data
        ports:
            - 5432:5432

    pgadmin:
        image: dpage/pgadmin4:latest
        env_file:
            - ./src/env/pgadmin.env
        ports:
            - 3000:80
volumes:
    data:
        external: true
